var ricercatoriNodes = new vis.DataSet([
    { id: 1, label: 'Arthur Evans', shape: "circularImage", image: "Images/ArthurEvans.jpg" },
    { id: 2, label: 'Heinrich Schliemann', shape: "circularImage", image: "Images/HeinrichSchliemann.jpg" },
    { id: 3, label: 'Ekaterina Petrovna Lyschin', shape: "circularImage", image: "Images/EkaterinaPetrovnaLyschin.jpg" },
    { id: 4, label: 'Agamennone' },
    { id: 5, label: 'Andromaca' },
    { id: 10, label: '', shape: "dot", size: 10, color: '#888' },
    { id: 11, label: '', shape: "dot", size: 10, color: '#888' },
    { id: 12, label: 'Sofia Egkastrōmenou', shape: "circularImage", image: "Images/SophiaEngastromenou.jpg" }
]);

var ricercatoriEdges = new vis.DataSet([
    { from: 2, to: 10 },
    { from: 3, to: 10 },
    { from: 11, to: 4 },
    { from: 11, to: 5 },
    { from: 2, to: 11 },
    { from: 12, to: 11 }
]);

var greekMythologyNodes = new vis.DataSet([
    { id: 'Zeus', label: 'Zeus (greci), Velcano (cretesi), Giove (romani)' },
    { id: 'Europa', label: 'Europa' },
    { id: 'Zeus+Europa', label: '', shape: "dot", size: 10, color: '#888' },
    { id: 'Minosse', label: 'Minosse' },
    { id: 'Pluto', label: 'Pluto' },
    { id: 'Zeus+Pluto', label: '', shape: "dot", size: 10, color: '#888' },
    { id: 'Tantalo', label: 'Tantalo' },
    { id: 'Pasife', label: 'Pasife' },
    { id: 'Fedra', label: 'Fedra' },
    { id: 'Arianna', label: 'Arianna' },
    { id: 'Minosse+Pasife', label: '', shape: "dot", size: 10, color: '#888' },
    { id: 'Toro', label: 'Toro' },
    { id: 'Minotauro', label: 'Minotauro' },
    { id: 'Toro+Pasife', label: '', shape: "dot", size: 10, color: '#888' },
    { id: 'Egeo', label: 'Egeo' },
    { id: 'Teseo', label: 'Teseo' },
    { id: 'Pelope', label: 'Pelope' },
    { id: 'Enomao', label: 'Enomao' },
    { id: 'Ippodamia', label: 'Ippodamia' },
    { id: 'Pelope+Ippodamia', label: '', shape: "dot", size: 10, color: '#888' },
    { id: 'Atreo', label: 'Atreo' },
    { id: 'Agamennone', label: 'Agamennone' },
    { id: 'Menelao', label: 'Menelao' },
    { id: 'Erope', label: 'Erope' },
    { id: 'Atreo+Erope', label: '', shape: "dot", size: 10, color: '#888' },
    { id: 'Tindareo', label: 'Tindareo' },
    { id: 'Leda', label: 'Leda' },
    { id: 'Tindareo+Leda', label: '', shape: "dot", size: 10, color: '#888' },
    { id: 'Clitennestra', label: 'Clitennestra' },
    { id: 'Elena', label: 'Elena' },
    { id: 'Oreste', label: 'Oreste' },
    { id: 'Agamennone+Clitennestra', label: '', shape: "dot", size: 10, color: '#888' },
    { id: 'Ulisse', label: 'Ulisse' },
    { id: 'Penelope', label: 'Penelope' },
    { id: 'Priamo', label: 'Priamo' },
    { id: 'Ecuba', label: 'Ecuba' },
    { id: 'Priamo+Ecuba', label: '', shape: "dot", size: 10, color: '#888' },
    { id: 'Ettore', label: 'Ettore' },
    { id: 'Paride', label: 'Paride' },
]);

var greekMythologyEdges = new vis.DataSet([
    { from: 'Zeus', to: 'Zeus+Europa' },
    { from: 'Europa', to: 'Zeus+Europa' },
    { from: 'Zeus+Europa', to: 'Minosse' },
    { from: 'Zeus', to: 'Zeus+Pluto' },
    { from: 'Pluto', to: 'Zeus+Pluto' },
    { from: 'Zeus+Pluto', to: 'Tantalo' },
    { from: 'Minosse', to: 'Minosse+Pasife' },
    { from: 'Pasife', to: 'Minosse+Pasife' },
    { from: 'Minosse+Pasife', to: 'Fedra' },
    { from: 'Minosse+Pasife', to: 'Arianna' },
    { from: 'Toro', to: 'Toro+Pasife' },
    { from: 'Pasife', to: 'Toro+Pasife' },
    { from: 'Toro+Pasife', to: 'Minotauro' },
    { from: 'Egeo', to: 'Teseo' },
    { from: 'Tantalo', to: 'Pelope' },
    { from: 'Enomao', to: 'Ippodamia' },
    { from: 'Pelope', to: 'Pelope+Ippodamia' },
    { from: 'Ippodamia', to: 'Pelope+Ippodamia' },
    { from: 'Pelope+Ippodamia', to: 'Atreo' },
    { from: 'Atreo', to: 'Atreo+Erope' },
    { from: 'Erope', to: 'Atreo+Erope' },
    { from: 'Atreo+Erope', to: 'Agamennone' },
    { from: 'Atreo+Erope', to: 'Menelao' },
    { from: 'Tindareo', to: 'Tindareo+Leda' },
    { from: 'Leda', to: 'Tindareo+Leda' },
    { from: 'Tindareo+Leda', to: 'Clitennestra' },
    { from: 'Tindareo+Leda', to: 'Elena' },
    { from: 'Menelao', to: 'Elena' },
    { from: 'Agamennone', to: 'Agamennone+Clitennestra' },
    { from: 'Clitennestra', to: 'Agamennone+Clitennestra' },
    { from: 'Agamennone+Clitennestra', to: 'Oreste' },
    { from: "Ulisse", to: "Penelope" },
    { from: 'Priamo', to: 'Priamo+Ecuba' },
    { from: 'Ecuba', to: 'Priamo+Ecuba' },
    { from: 'Priamo+Ecuba', to: 'Ettore' },
    { from: 'Priamo+Ecuba', to: 'Paride' },
    { from: 'Elena', to: 'Paride' },
]);